export const TEAMS = [
  { id: 'man-utd',   name: 'Manchester United',  shortName: 'MUN', primaryColor: '#DA291C' },
  { id: 'tottenham', name: 'Tottenham Hotspur',   shortName: 'TOT', primaryColor: '#132257' },
  { id: 'arsenal',   name: 'Arsenal',             shortName: 'ARS', primaryColor: '#EF0107' },
  { id: 'liverpool', name: 'Liverpool',           shortName: 'LIV', primaryColor: '#C8102E' },
  { id: 'chelsea',   name: 'Chelsea',             shortName: 'CHE', primaryColor: '#034694' },
  { id: 'man-city',  name: 'Manchester City',     shortName: 'MCI', primaryColor: '#6CABDD' },
];

export const POSTS = [
  // ── p1: 카세미루 이별 오피셜 (debate) ──────────────────────────
  {
    id: 'p1',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '카세미루,\n맨유와 이별 오피셜',
    summary: '첫 시즌과 마지막 시즌은 레전드급. 그 사이 2~3시즌이 문제다.',
    tweet: {
      author: 'Samuel Luckhurst',
      initials: 'SL',
      handle: '@samuelluckhurst',
      tier: 2,
      text: '카세미루는 경기 후 기자회견에 참석할 예정이었지만 결국 "너무 감정적"이라서 진행하지 못했습니다. 막대한 연봉을 받았지만 맨유에서의 시간 동안 분명히 헌신적이었고, 관중들과 진정한 유대감을 형성했습니다.',
      timeAgo: '11시간 전',
    },
    club: 'MUN',
    status: 'Official',
    hashtags: ['#카세미루', '#맨유', '#이별'],
    reactions: 3200,
    comments: 1890,
    bookmarks: 421,
    shares: 134,
    voteFor: 35,
    voteAgainst: 65,
    voteForLabel: '성공한 영입',
    voteAgainstLabel: '실패한 영입',
    participants: 1890,
    recentTrend: { pct: 5, direction: 'against', time: '30분' },
    debateQuestion: '카세미루 영입, 성공이었나 실패였나?',
    aiNarrative: '트로피도 들었고 마지막 시즌도 임팩트가 있었다. 하지만 가운데 2~3시즌의 성적과 연봉을 생각하면 의문이 남는다.',
    aiSummary: {
      for: ['첫 시즌 수비 안정감 확실', '리그컵 우승 기여', '마지막 시즌도 존재감 강했다', '팬들과의 유대감은 진짜였다'],
      against: ['중간 시즌 퍼포먼스 하락이 뼈아팠다', '연봉 대비 총 기여도 의문', '그 돈이면 더 좋은 선택 가능했다'],
    },
    argumentPoints: [
      { id: 'a1', text: '첫 시즌 + 마지막 시즌은 레전드급 퍼포먼스', stance: 'for', comments: 182 },
      { id: 'a2', text: '중간 시즌들이 너무 실망스러웠다', stance: 'against', comments: 241 },
      { id: 'a3', text: '눈물의 이별 — 팬과의 유대는 진짜였다', stance: 'neutral', comments: 92 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'RC', user: '@redcafe_88', club: 'MUN', timeAgo: '2시간', text: '맨유 팬 입장에서는 그냥 실패다. 1억 쓰고 중간 3시즌 버렸잖아', likes: 723, stance: 'against' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_history', club: 'MUN', timeAgo: '3시간', text: '첫 시즌은 진짜 좋았다. 리그컵 들었고. 문제는 그 이후였지', likes: 512, stance: 'for' },
      { id: 3, rank: '03', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '4시간', text: '감정적이라 기자회견 못 했다는 게 오히려 더 사람 같아 보임', likes: 389 },
      { id: 4, rank: '04', initials: 'MK', user: '@mancunian_kr', club: 'MUN', timeAgo: '5시간', text: '이번 시즌 카세미루 없을 때 팀이 얼마나 흔들렸는지 봤잖아. 그게 다야', likes: 234, stance: 'for' },
    ],
  },

  // ── p2: 칸셀루 바르사 잔류? (debate) ───────────────────────────
  {
    id: 'p2',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '칸셀루, 바르사 잔류?\n사우디 복귀?',
    summary: '사우디에서 임대 온 칸셀루 — 플리크의 신임 vs 알 힐랄 복귀 압박.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      text: '한시 플리크, 칸셀루 잔류에 대해: "쉽지 않지만 데코가 처리 중입니다. 최근 경기에서 칸셀루가 우리에게 무엇을 줬는지 모두가 알고 있어요. 환상적인 선수입니다. 정말 많이 아낍니다."',
      timeAgo: '5시간 전',
    },
    club: 'MCI',
    status: 'Talks',
    hashtags: ['#칸셀루', '#바르셀로나', '#사우디'],
    reactions: 2800,
    comments: 1540,
    bookmarks: 312,
    shares: 98,
    voteFor: 74,
    voteAgainst: 26,
    voteForLabel: '바르사 잔류',
    voteAgainstLabel: '사우디 복귀',
    participants: 1540,
    recentTrend: { pct: 6, direction: 'for', time: '1시간' },
    debateQuestion: '칸셀루, 바르사에 남아야 할까? 사우디로 돌아가야 할까?',
    aiNarrative: '알 힐랄에서 임대 온 칸셀루는 플리크 체제에서 완전히 살아났다. 하지만 바르사의 재정 불안과 알 힐랄의 복귀 요청이 걸림돌이다.',
    aiSummary: {
      for: ['플리크 체제에서 이번 시즌 커리어 최고폼', '바르셀로나 전술에 완벽히 최적화됨', '사우디 복귀는 커리어 사실상 종료'],
      against: ['알 힐랄 임대 계약 조건상 복귀 압박', '바르사 재정 불안 — 영구 계약은 불투명', '챔피언스리그 출전이 더 이상 보장 아님'],
    },
    argumentPoints: [
      { id: 'b1', text: '플리크 체제에서 커리어 최고폼 중', stance: 'for', comments: 198 },
      { id: 'b2', text: '사우디 복귀는 커리어 사실상 종료', stance: 'for', comments: 154 },
      { id: 'b3', text: '바르사 재정 불안 — 잔류 보장 없다', stance: 'against', comments: 211 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BF', user: '@barca_fan_kr', club: 'MCI', timeAgo: '1시간', text: '이번 시즌 칸셀루 없었으면 챔스 어땠을지... 무조건 잔류', likes: 634, stance: 'for' },
      { id: 2, rank: '02', initials: 'PL', user: '@prem_legacy', club: 'MCI', timeAgo: '2시간', text: '사우디 가면 커리어 끝나는 거다. 플리크 믿고 가야지', likes: 445, stance: 'for' },
      { id: 3, rank: '03', initials: 'FK', user: '@football_kr', club: 'MCI', timeAgo: '3시간', text: '알 힐랄이 복귀 원하는 이상 바르사가 돈 내야 하는데 과연 가능한가', likes: 267, stance: 'against' },
    ],
  },

  // ── p3: 브루노 20어시 달성 (today_debate) ──────────────────────
  {
    id: 'p3',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '브루노 20어시 달성,\n마지막 라운드 기록 경신?',
    summary: '앙리·데 브라이너와 EPL 역대 타이기록. 1라운드 남았다.',
    tweet: {
      author: 'Simon Stone',
      initials: 'SS',
      handle: '@sistoney67',
      tier: 2,
      text: '브루노 페르난데스: "19개가 됐을 때 생각이 들기 시작했어요. 티에리와 케빈 얘기를 하는 거잖아요 — EPL의 메인 이름들이죠. 21개가 되면 좋겠지만 안 돼도 괜찮아요. 20어시도 해본 적 없었으니까."',
      timeAgo: '1시간 전',
    },
    club: 'MUN',
    status: 'Opinion',
    hashtags: ['#브루노', '#어시스트기록', '#EPL역사'],
    reactions: 4100,
    comments: 2890,
    bookmarks: 678,
    shares: 312,
    voteFor: 61,
    voteAgainst: 39,
    voteForLabel: '21어시 신기록',
    voteAgainstLabel: '20어시 마감',
    participants: 2890,
    recentTrend: { pct: 8, direction: 'for', time: '30분' },
    debateQuestion: '마지막 라운드, 브루노 21어시 신기록 달성 가능?',
    aiNarrative: '단 1라운드 남았다. 앙리·데 브라이너와 어깨를 나란히 한 브루노 — 역사를 다시 쓸 수 있을까?',
    aiSummary: {
      for: ['현재 폼이 시즌 내내 최고 수준 유지', '마지막 경기 강력한 동기부여 확실', '이미 심리적 장벽을 넘은 상태'],
      against: ['상대팀이 집중 견제할 게 뻔하다', '단 1경기에서 어시스트 보장 없음', '팀 전술적 필요에 따라 달라질 수도'],
    },
    argumentPoints: [
      { id: 'c1', text: '현재 폼이면 21어시 충분히 가능', stance: 'for', comments: 312 },
      { id: 'c2', text: '상대팀 집중 견제가 변수', stance: 'against', comments: 278 },
      { id: 'c3', text: '20어시 자체가 이미 역사적 기록', stance: 'neutral', comments: 145 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BK', user: '@brunokr_fan', club: 'MUN', timeAgo: '30분', text: '앙리급 시즌이다. 21개 간다', likes: 1023, stance: 'for' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_numbers', club: 'MUN', timeAgo: '45분', text: '상대팀이 집중 마크할 텐데... 쉽지 않다', likes: 756, stance: 'against' },
      { id: 3, rank: '03', initials: 'MF', user: '@midfield_kr', club: 'MUN', timeAgo: '1시간', text: '20어시도 역대급인데 21까지? 이 세대 최고의 미드필더', likes: 534, stance: 'for' },
      { id: 4, rank: '04', initials: 'RC', user: '@redcafe_88', club: 'MUN', timeAgo: '1시간', text: '이 선수 팔자고? 기록 보고도 매각설 나오면 진짜 ㅋㅋ', likes: 445 },
    ],
  },

  // ── p4: 캐릭 맨유 감독 거피셜 (debate) ────────────────────────
  {
    id: 'p4',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '캐릭 맨유 감독 거피셜,\n내년 시즌 성공할까?',
    summary: '레전드가 감독직에 도전한다. 경험 부족 우려 vs 클럽 DNA 적임자.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      text: 'Michael Carrick set to be named Manchester United head coach. Discussions ongoing with the board. Decision expected soon. Here We Go soon! 🔴',
      timeAgo: '3시간 전',
    },
    club: 'MUN',
    status: 'Advanced',
    hashtags: ['#캐릭', '#맨유감독', '#리빌딩'],
    reactions: 2900,
    comments: 2100,
    bookmarks: 445,
    shares: 167,
    voteFor: 44,
    voteAgainst: 56,
    voteForLabel: '성공 가능',
    voteAgainstLabel: '회의적',
    participants: 2100,
    recentTrend: { pct: 3, direction: 'against', time: '1시간' },
    debateQuestion: '캐릭 감독 체제, 내년 시즌 성공할 수 있을까?',
    aiNarrative: '클럽 레전드가 감독직에 오른다. 경험 부족을 우려하는 시각과, 맨유 DNA를 아는 적임자라는 기대가 충돌 중이다.',
    aiSummary: {
      for: ['맨유 클럽 문화를 누구보다 잘 이해', '선수들과의 유대관계 이미 형성됨', '미들즈브러 감독직 현장 경험 보유'],
      against: ['최고 수준 감독 경력 전무', '리빌딩 상황에선 검증된 감독 필요', '전술적 유연성 아직 검증 안 됨'],
    },
    argumentPoints: [
      { id: 'd1', text: '맨유 DNA를 아는 감독이 필요한 시점', stance: 'for', comments: 267 },
      { id: 'd2', text: '최고 수준 감독 경력이 전무하다', stance: 'against', comments: 334 },
      { id: 'd3', text: '이적시장 보강이 성패를 가른다', stance: 'neutral', comments: 189 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '30분', text: '레전드가 맡는 건 좋은데 지금이 타이밍이 맞나? 경험이 너무 부족해', likes: 834, stance: 'against' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_history', club: 'MUN', timeAgo: '1시간', text: '일단 믿어보자. 맨유를 누구보다 잘 아는 사람이잖아', likes: 567, stance: 'for' },
      { id: 3, rank: '03', initials: 'SA', user: '@sir_alex_', club: 'MUN', timeAgo: '1시간', text: '전술 스태프 잘 꾸리면 가능하다. 퍼거슨도 처음엔 의심받았음', likes: 412, stance: 'for' },
      { id: 4, rank: '04', initials: 'MK', user: '@mancunian_kr', club: 'MUN', timeAgo: '2시간', text: '이적시장 뭘 데려오느냐에 달려있다. 감독 혼자서는 답 없음', likes: 298 },
    ],
  },

  // ── p5: 네이마르 월드컵 발탁 논란 (debate) ─────────────────────
  {
    id: 'p5',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '네이마르, 34세에\n월드컵 발탁 논란',
    summary: '안첼로티가 오랜 부상 역사의 네이마르를 브라질 스쿼드에 포함. 주앙 페드로는 탈락.',
    tweet: {
      author: 'The Athletic | Football',
      initials: 'TA',
      handle: '@TheAthletic',
      tier: 1,
      text: "Neymar is going to the World Cup. Carlo Ancelotti has seen fit to include the 34-year-old in his Brazil squad for this summer's tournament. Brentford's Igor Thiago and Bournemouth's Rayan have also been selected — but there is no place for Chelsea's Joao Pedro.",
      timeAgo: '7시간 전',
    },
    status: 'Official',
    hashtags: ['#네이마르', '#브라질', '#월드컵'],
    reactions: 4800,
    comments: 3200,
    bookmarks: 620,
    shares: 289,
    voteFor: 31,
    voteAgainst: 69,
    voteForLabel: '발탁 찬성',
    voteAgainstLabel: '세대교체해야',
    participants: 3200,
    recentTrend: { pct: 9, direction: 'against', time: '1시간' },
    debateQuestion: '네이마르 월드컵 발탁, 옳은 결정인가?',
    aiNarrative: '34살, 오랜 부상 공백, 현재 폼 물음표. 그럼에도 안첼로티는 네이마르를 택했다. 팬들은 주앙 페드로 같은 젊은 피를 원한다.',
    aiSummary: {
      for: ['월드컵 경험치는 아직 아무도 못 따라온다', '안첼로티가 폼을 직접 확인한 결정', '네이마르의 동기부여는 역대급일 것'],
      against: ['주앙 페드로를 포함시켰어야 했다', '부상 리스크가 너무 높다', '34살에 월드컵 체력은 다른 문제'],
    },
    argumentPoints: [
      { id: 'n1', text: '경험과 네임밸류만큼은 여전히 압도적', stance: 'for', comments: 289 },
      { id: 'n2', text: '주앙 페드로 탈락은 납득 불가', stance: 'against', comments: 412 },
      { id: 'n3', text: '부상 위험 — 월드컵에서 버틸 수 있을까', stance: 'against', comments: 356 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BR', user: '@brazil_kr', timeAgo: '2시간', text: '안첼로티가 폼 보고 뽑은 거잖아. 믿어보자', likes: 892, stance: 'for' },
      { id: 2, rank: '02', initials: 'JK', user: '@joaopedro_fan', timeAgo: '3시간', text: '주앙 페드로 팬으로서 진짜 납득이 안 감. 첼시에서 활약 중인데', likes: 734, stance: 'against' },
      { id: 3, rank: '03', initials: 'WC', user: '@worldcup_kr', timeAgo: '4시간', text: '부상 이력이 너무 많다. 개인적으로 걱정된다', likes: 521, stance: 'against' },
      { id: 4, rank: '04', initials: 'FK', user: '@football_kr', timeAgo: '5시간', text: '2022 카타르에서도 부상났잖아... 이번엔 버텨줄까', likes: 412 },
    ],
  },

  // ── p6: 펩 과르디올라 맨시티 이별 (sentimental) ────────────────
  {
    id: 'p6',
    type: 'sentimental',
    title: '펩 과르디올라,\n맨시티와 이별',
    summary: '9년간 6번의 리그 우승, 챔피언스리그 우승까지. 이제 시대가 끝난다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      text: 'Pep Guardiola has informed Manchester City that he will leave the club this summer. Decision confirmed and official statement to follow as Pep will say goodbye to Man City fans very soon. Only one name to replace Pep: Enzo Maresca.',
      timeAgo: '6시간 전',
    },
    club: 'MCI',
    status: 'Official',
    hashtags: ['#펩과르디올라', '#맨시티', '#이별'],
    reactions: 12400,
    comments: 2890,
    bookmarks: 1890,
    shares: 789,
    gradientFrom: '#001a38',
    accentColor: '#6dc1e7',
    icon: '🔵',
    comments_data: [
      { id: 1, rank: '01', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '30분', text: '9년간 감사했습니다. 역사상 최고의 감독이었습니다', likes: 4231 },
      { id: 2, rank: '02', initials: 'BL', user: '@blue_legacy', club: 'MCI', timeAgo: '45분', text: '제발 1년만 더... 마지막으로 챔스 한 번만', likes: 3456 },
      { id: 3, rank: '03', initials: 'GG', user: '@guardiola_way', club: 'MCI', timeAgo: '1시간', text: '펩 없는 맨시티는 상상이 안 된다. 한 시대가 진짜 끝났다', likes: 2891 },
      { id: 4, rank: '04', initials: 'EM', user: '@etihad_memories', club: 'MCI', timeAgo: '1시간', text: '마르체스카가 후임이라고? 펩 그림자가 너무 크다', likes: 1823 },
    ],
  },

  // ── p7: 카이 하베르츠 결승골 / 아스날 우승 (today_debate) ───────
  {
    id: 'p7',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '하베르츠 결승골,\n아스날 우승 가능?',
    summary: '번리전 1-0 승리로 우승 3점 차. 마지막 라운드에 모든 것이 걸렸다.',
    tweet: {
      author: 'Sky Sports Premier League',
      initials: 'SS',
      handle: '@SkySports',
      tier: 1,
      text: "FULL-TIME: Kai Havertz's strike seals the win, putting the Gunners within three points of the Premier League title! 🏆🔴",
      timeAgo: '8시간 전',
    },
    club: 'ARS',
    status: 'Opinion',
    hashtags: ['#아스날', '#하베르츠', '#EPL우승'],
    reactions: 5600,
    comments: 3100,
    bookmarks: 789,
    shares: 445,
    voteFor: 54,
    voteAgainst: 46,
    voteForLabel: '우승 가능',
    voteAgainstLabel: '또 무너진다',
    participants: 3100,
    recentTrend: { pct: 4, direction: 'for', time: '30분' },
    debateQuestion: '아스날, 이번 시즌 마침내 우승할 수 있을까?',
    aiNarrative: '마지막 라운드, 단 3점 차. 하베르츠의 결승골로 희망을 이어갔다. 하지만 역사는 반복되는가 — 아스날은 또 무너질 것인가?',
    aiSummary: {
      for: ['현재 폼이 시즌 내내 최고 수준', '하베르츠의 결정력이 살아났다', '이번엔 다르다, 경험이 쌓였다'],
      against: ['마지막 라운드에서 아스날은 항상 무너진다', '선두는 3점 차 이상이 필요했다', '아르테타의 빅게임 운영이 여전히 걱정'],
    },
    argumentPoints: [
      { id: 'f1', text: '하베르츠, 이번 시즌 가장 중요한 골맨', stance: 'for', comments: 267 },
      { id: 'f2', text: '아스날은 타이틀 레이스마다 흔들렸다', stance: 'against', comments: 334 },
      { id: 'f3', text: '마지막 라운드 상대팀 일정이 관건', stance: 'neutral', comments: 198 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '1시간', text: '이번엔 진짜 된다. 하베르츠 폼 보라', likes: 1234, stance: 'for' },
      { id: 2, rank: '02', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '1시간', text: '16-17 이후 너무 오래됐다... 제발 이번엔', likes: 987, stance: 'for' },
      { id: 3, rank: '03', initials: 'EK', user: '@epl_kr', club: 'ARS', timeAgo: '2시간', text: '아스날 팬이지만 솔직히 마지막 라운드 믿음이 안 간다', likes: 756, stance: 'against' },
      { id: 4, rank: '04', initials: 'PL', user: '@prem_legacy', timeAgo: '2시간', text: '상대팀 일정 봐야지. 섣불리 판단 이르다', likes: 543 },
    ],
  },

  // ── p8: 호날두 올드 트래퍼드 마지막 장면 (sentimental) ──────────
  {
    id: 'p8',
    type: 'sentimental',
    title: '호날두의 올드 트래퍼드\n마지막 장면이 오늘로 3년',
    summary: '2022년 5월, 눈물을 흘리며 올드 트래퍼드를 떠난 그날.',
    club: 'MUN',
    status: 'Memory',
    hashtags: ['#호날두', '#올드트래퍼드', '#레전드'],
    reactions: 8700,
    comments: 432,
    bookmarks: 1200,
    shares: 234,
    gradientFrom: '#3b0000',
    accentColor: '#e63946',
    icon: '🔴',
    comments_data: [
      { id: 1, rank: '01', initials: 'CR', user: '@cr7_forever', club: 'MUN', timeAgo: '10분', text: '3년이 지나도 그 장면은 잊히지가 않는다', likes: 2341 },
      { id: 2, rank: '02', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '15분', text: '유나이티드가 그를 제대로 보내줬어야 했는데', likes: 1823 },
      { id: 3, rank: '03', initials: 'MU', user: '@mufc_legend', club: 'MUN', timeAgo: '20분', text: '2008년 챔피언스리그... 그 시절이 그립다', likes: 1456 },
    ],
  },

  // ── p9: 홀란드 부상 (general) ───────────────────────────────────
  {
    id: 'p9',
    type: 'general',
    title: '맨시티, 홀란드\n무릎 부상 6~8주 이탈',
    summary: '시즌 막판 직격탄. 챔스 준결승 출전도 불투명해졌다.',
    tweet: {
      author: 'David Ornstein',
      initials: 'DO',
      handle: '@David_Ornstein',
      tier: 1,
      text: 'Erling Haaland facing 6-8 weeks out with knee injury sustained in training. Doubt for Champions League semi-finals. 🔵',
      timeAgo: '1시간 전',
    },
    club: 'MCI',
    status: 'Official',
    hashtags: ['#홀란드', '#맨시티', '#부상'],
    reactions: 3100,
    comments: 234,
    bookmarks: 145,
    shares: 67,
    comments_data: [
      { id: 1, rank: '01', initials: 'MC', user: '@mcfc_sky', club: 'MCI', timeAgo: '20분', text: '챔스 준결승 없이는 이 시즌이 의미 없다', likes: 523 },
      { id: 2, rank: '02', initials: 'BL', user: '@blue_legacy', club: 'MCI', timeAgo: '35분', text: '홀란드 없어도 뎁스가 있다. 너무 걱정 마라', likes: 334 },
      { id: 3, rank: '03', initials: 'GG', user: '@guardiola_way', club: 'MCI', timeAgo: '45분', text: '이 타이밍에 부상이라니... 시즌 최악의 뉴스', likes: 289 },
    ],
  },
];
