export const TEAMS = [
  { id: 'man-utd',   name: 'Manchester United',  shortName: 'MUN', primaryColor: '#DA291C' },
  { id: 'tottenham', name: 'Tottenham Hotspur',   shortName: 'TOT', primaryColor: '#132257' },
  { id: 'arsenal',   name: 'Arsenal',             shortName: 'ARS', primaryColor: '#EF0107' },
  { id: 'liverpool', name: 'Liverpool',           shortName: 'LIV', primaryColor: '#C8102E' },
  { id: 'chelsea',   name: 'Chelsea',             shortName: 'CHE', primaryColor: '#034694' },
  { id: 'man-city',  name: 'Manchester City',     shortName: 'MCI', primaryColor: '#6CABDD' },
];

export const POSTS = [
  // ── p20: 맷 로 튀르키예 국기 — 일디즈 vs 귈러 (hot_debate / CHE) ──
  {
    id: 'p20',
    type: 'hot_debate',
    badge: 'HOT DEBATE',
    title: '맷 로, 튀르키예 국기 게시\n첼시 이적 힌트?',
    summary: '첼시 핵심 기자 맷 로가 설명 없이 튀르키예 국기를 올렸다. 현재 첼시와 연결되는 튀르키예 국적 선수로는 유벤투스 윌디즈가 거론되고 있다.',
    briefing: '첼시 핵심 기자 맷 로가 설명 없이 튀르키예 국기만 게시했다. 맷 로는 과거에도 이런 방식으로 이적 힌트를 남긴 전례가 있어 팬들의 관심이 집중되고 있다. 현재 첼시와 연결되는 튀르키예 국적 선수로는 유벤투스 소속 케난 윌디즈가 유력하게 거론되고 있으며, 레알 마드리드 아르다 귈러의 이름도 일부 팬들 사이에서 언급되고 있다. 다만 맷 로는 현재까지 어떤 선수도 구체적으로 지목하지 않았다.',
    tweet: {
      author: 'Matt Law',
      initials: 'ML',
      handle: '@Matt_Law_DT',
      tier: 1,
      timeAgo: '방금',
    },
    imageUrl: 'https://blog.kakaocdn.net/dna/bDXO6J/btsOe1XqL6F/AAAAAAAAAAAAAAAAAAAAAJHzQOVmWJgq8195W46Pd1UFawm5OPgHIKT7eUTDQ92C/img.jpg?credential=yqXZFxpELC7KVnFOS48ylbz2pIh7yKj8&expires=1780239599&allow_ip=&allow_referer=&signature=FaAc8R3bo9l6y4Cp3Kk8O89Fkho%3D',
    club: 'CHE',
    status: 'Rumour',
    hashtags: ['#첼시', '#윌디즈', '#귈러', '#이적루머'],
    reactions: 6200,
    comments: 3100,
    bookmarks: 890,
    shares: 410,
    voteFor: 61,
    voteAgainst: 39,
    voteForLabel: '윌디즈',
    voteAgainstLabel: '귈러',
    participants: 3100,
    recentTrend: { pct: 4, direction: 'for', time: '30분' },
    debateQuestion: '첼시에 더 필요한 영입은?',
    aiNarrative: '맷 로의 튀르키예 국기 한 장이 팬들 사이에서 논쟁을 불러일으켰다. 윌디즈냐 귈러냐 — 첼시 팬들의 의견이 갈리고 있다.',
    aiSummary: {
      for: ['윌디즈는 유벤투스에서 이미 주전으로 증명됐다', '첼시 스타일에 맞는 직선적인 드리블과 슈팅', '나이(20) 대비 완성도가 높아 즉전감으로 손색없다'],
      against: ['귈러는 레알 마드리드 출신 — 잠재력이 다르다', '창의성과 패스 능력은 귈러가 한 수 위라는 평가', '아직 어리지만 대형 클럽 경험치를 갖고 있다'],
    },
    argumentPoints: [
      { id: 'c1', text: '윌디즈 — 유벤투스에서 검증된 즉전감 확보', stance: 'for', comments: 412 },
      { id: 'c2', text: '귈러 — 레알 출신, 장기적으로 더 큰 그림이다', stance: 'against', comments: 356 },
      { id: 'c3', text: '둘 다 좋지만 포지션 중복 고려해야 한다', stance: 'neutral', comments: 198 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'CK', user: '@chelsea_kr', club: 'CHE', timeAgo: '5분', text: '맷 로가 이 식으로 올리면 진짜라는 거 첼시 팬이면 다 안다', likes: 2341, stance: 'for' },
      { id: 2, rank: '02', initials: 'WD', user: '@yildiz_fan', club: 'CHE', timeAgo: '10분', text: '윌디즈 영입이면 진짜 기대된다. 유벤투스에서 이미 검증됐잖아', likes: 1876, stance: 'for' },
      { id: 3, rank: '03', initials: 'AG', user: '@guler_watch', timeAgo: '15분', text: '귈러도 가능성 있다. 레알에서 출전 기회 못 받고 있어서 이적 가능성 있음', likes: 1234, stance: 'against' },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '20분', text: '맷 로 국기 시리즈는 거의 적중률 100% 아니었나. 기대된다', likes: 987 },
    ],
  },

  // ── p17: 아스날 21년 만에 우승 확정 (today_debate / ARS) ──────────
  {
    id: 'p17',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '아스날 21년 만에\n우승 확정',
    summary: '맨시티가 본머스와 1:1 무승부. 아스날이 마지막 라운드를 앞두고 21년 만의 우승을 확정지었다.',
    briefing: '새뮤얼 럭허스트 보도다. 맨시티가 본머스에 발목이 잡히며 아스날의 21년 만의 리그 우승이 최종 확정됐다. 럭허스트는 "아스날은 항상 이번 시즌 이길 팀이었다"며, 스토크·볼턴·블랙번에 치이던 시절에서 완전히 달라진 팀이 됐다고 평가했다.',
    tweet: {
      author: 'Samuel Luckhurst',
      initials: 'SL',
      handle: '@samuelluckhurst',
      tier: 2,
      timeAgo: '3시간 전',
    },
    imageUrl: 'https://pbs.twimg.com/media/HItdVOVXUAE-IWH.jpg',
    club: 'ARS',
    status: 'Official',
    hashtags: ['#아스날', '#EPL우승', '#21년만에'],
    reactions: 18900,
    comments: 8200,
    bookmarks: 3400,
    shares: 2100,
    voteFor: 74,
    voteAgainst: 26,
    voteForLabel: '자격 있었다',
    voteAgainstLabel: '운이었다',
    participants: 8200,
    recentTrend: { pct: 5, direction: 'for', time: '30분' },
    debateQuestion: '아스날, 이번 시즌 우승할 자격이 있었나?',
    aiNarrative: '21년의 기다림이 끝났다. 아스날이 마침내 챔피언이 됐다. 하지만 맨시티의 자멸로 확정됐다는 시각도 있어 팬들 사이 의견이 갈린다.',
    aiSummary: {
      for: ['시즌 내내 가장 일관된 퍼포먼스를 보여줬다', '하베르츠·라야 등 결정적 순간마다 팀을 살렸다', '아르테타 체제의 성장이 눈에 띄게 뚜렷했다'],
      against: ['맨시티가 알아서 무너진 면이 분명히 있다', '빅게임 직접 맞대결 성적을 따져봐야 한다', '운의 요소도 무시할 수 없다'],
    },
    argumentPoints: [
      { id: 'ar1', text: '시즌 내내 가장 안정적 — 아르테타의 완성형 팀', stance: 'for', comments: 567 },
      { id: 'ar2', text: '맨시티 자멸 덕분에 확정됐다는 느낌이 든다', stance: 'against', comments: 312 },
      { id: 'ar3', text: '21년의 기다림 자체가 이미 충분한 자격이다', stance: 'neutral', comments: 445 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '30분', text: '드디어... 21년이다. 눈물 난다', likes: 5643, stance: 'for' },
      { id: 2, rank: '02', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '45분', text: '아르테타 정말 대단하다. 이 팀을 여기까지 만들었다', likes: 4231, stance: 'for' },
      { id: 3, rank: '03', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '1시간', text: '맨시티 팬으로서 인정한다. 이번 시즌은 아스날이 더 나았다', likes: 2891, stance: 'for' },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '1시간', text: '자격 논쟁이 무슨 의미가 있냐. 이긴 팀이 챔피언이다', likes: 2134 },
    ],
  },

  // ── p18: 펩 과르디올라 아스날 축하 (sentimental / MCI) ────────────
  {
    id: 'p18',
    type: 'sentimental',
    title: '펩 과르디올라,\n"축하한다, 아스날"',
    summary: '라이벌에게 건네는 한 마디. 10년간 EPL을 지배한 펩이 아스날의 우승을 직접 인정했다.',
    briefing: '파브리지오 로마노 보도다. 펩 과르디올라가 아스날을 향해 "Congratulations, Arsenal"이라는 한 마디를 남겼다. 맨시티를 이끌며 리그를 지배했던 감독이, 올 시즌 자신의 팀을 꺾은 라이벌의 우승을 담담하게 인정한 장면이다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '1시간 전',
    },
    imageUrl: 'https://d2x51gyc4ptf2q.cloudfront.net/content/uploads/2026/05/19212211/man-city-manager-pep-guardiola-1320x742.jpg',
    club: 'MCI',
    status: 'Official',
    hashtags: ['#펩과르디올라', '#아스날우승', '#라이벌'],
    reactions: 9800,
    comments: 2100,
    bookmarks: 1230,
    shares: 678,
    gradientFrom: '#001a38',
    accentColor: '#6dc1e7',
    icon: '🔵',
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '20분', text: '펩이 직접 축하해줬다. 이게 진짜 챔피언의 무게감이다', likes: 3421 },
      { id: 2, rank: '02', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '30분', text: '맨시티 팬이지만 펩다운 모습이다. 품격 있다', likes: 2678 },
      { id: 3, rank: '03', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '45분', text: '아스날 팬으로서 펩한테 받는 축하가 더 의미 있게 느껴진다', likes: 2134 },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '1시간', text: '10년 라이벌 구도가 이렇게 마무리되는 거 보니까 진짜 한 시대가 끝났다는 게 실감난다', likes: 1567 },
    ],
  },

  // ── p21: 이안 라이트 팬들과 자축 (sentimental / ARS) ────────────
  {
    id: 'p21',
    type: 'sentimental',
    title: '이안 라이트,\n"우리가 받을 자격이 있다"',
    summary: '아스날 레전드 이안 라이트가 우승 확정 직후 팬들과 함께 자축에 나섰다. "지난 3년이 너무 힘들었는데 마침내 해냈다"며 기쁨을 감추지 못했다.',
    briefing: '아스날 레전드 이안 라이트가 우승 확정 직후 팬들과 함께 거리로 나와 자축에 참여했다. 라이트는 "지난 3년이 정말 힘들었는데 마침내 해냈다. 솔직히 무슨 말을 해야 할지 모르겠다. 정말 대단하다"고 소감을 전했다. 이어 "이 클럽은 이걸 받을 자격이 있고, 전 세계 팬들도 마찬가지다. 우리 모두가 이걸 받을 자격이 있다"고 덧붙였다. 파브리지오 로마노가 라이트의 발언을 인용해 전했다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '3시간 전',
    },
    imageUrl: 'https://mblogthumb-phinf.pstatic.net/MjAyMTEwMDRfMjkz/MDAxNjMzMzM5NzU1MDYz.DJPaTBltzhriJkUN5ktTtR_F0U-bCNw4Ax3aHieeSLQg._Vga5sdJWAoQthjq7AJXRp1oorl7VioOEwOG_rbPltMg.JPEG.skdbwhdrb/IMG_2251.JPG?type=w800',
    club: 'ARS',
    status: 'Official',
    hashtags: ['#이안라이트', '#아스날우승', '#자축'],
    reactions: 11000,
    comments: 2800,
    bookmarks: 1100,
    shares: 890,
    gradientFrom: '#1a0505',
    accentColor: '#ef0107',
    icon: '❤️',
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '30분', text: '라이트 형 눈물 나게 하지 마라... 나도 울었다', likes: 4123 },
      { id: 2, rank: '02', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '45분', text: '이 클럽과 함께한 레전드가 팬들 사이로 뛰어든 거잖아. 진짜 장면이다', likes: 3456 },
      { id: 3, rank: '03', initials: 'EK', user: '@epl_kr', timeAgo: '1시간', text: '"We deserve this" — 21년 기다린 팬들한테 라이트가 해줄 수 있는 최고의 말이다', likes: 2789 },
      { id: 4, rank: '04', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '1시간', text: '라이트가 팬들 사이에 들어간 거 보고 나도 뭔가 느꼈다. 인정한다', likes: 1567 },
    ],
  },

  // ── p22: 맥스 다우먼 EPL 최연소 우승자 (sentimental / ARS) ─────────
  {
    id: 'p22',
    type: 'sentimental',
    title: '다우먼, EPL 역대\n최연소 우승자 등극',
    summary: '맥스 다우먼이 16세 139일의 나이로 EPL 역대 최연소 우승자 기록을 세웠다. 아스날의 리그 우승 멤버에 이름을 올리며 역사를 새로 썼다.',
    briefing: '아스날 소속 맥스 다우먼이 16세 139일의 나이로 EPL 역대 최연소 우승자 기록을 수립했다. 다우먼은 이번 시즌 아스날 1군에 등록돼 우승 멤버로 이름을 올렸다. 16세의 나이에 리그 우승 메달을 차지한 선수는 EPL 역사상 전례가 없는 것으로 알려졌다. 파브리지오 로마노가 이 기록을 직접 전하며 주목받고 있다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '19분 전',
    },
    imageUrl: 'https://e0.365dm.com/25/08/1600x900/skysports-max-dowman-arsenal_7000574.jpg?20250824214153',
    club: 'ARS',
    status: 'Official',
    hashtags: ['#맥스다우먼', '#아스날', '#최연소우승'],
    reactions: 9000,
    comments: 2100,
    bookmarks: 980,
    shares: 670,
    gradientFrom: '#1a0808',
    accentColor: '#ef0107',
    icon: '🏆',
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '10분', text: '16세 139일... 말이 되는 숫자냐. 이 클럽 진짜 뭔가 있다', likes: 3812 },
      { id: 2, rank: '02', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '15분', text: '우승 멤버에 이름 올릴 때 나이가 16살이라니. 앞으로가 더 기대되는 선수다', likes: 2943 },
      { id: 3, rank: '03', initials: 'EK', user: '@epl_kr', timeAgo: '20분', text: 'EPL 130년 역사에서 최연소 우승. 숫자가 그냥 레전드다', likes: 2156 },
      { id: 4, rank: '04', initials: 'PL', user: '@prem_legacy', timeAgo: '25분', text: '등번호 56번이 이 기록을 갖게 될 줄은 몰랐다', likes: 1478 },
    ],
  },

  // ── p16: 토트넘 강등권 마지막 라운드 (today_debate / TOT) ─────────
  {
    id: 'p16',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '데제르비 "강등 회피가\n트로피보다 중요"',
    summary: '첼시에 2:1 패배로 강등권 탈출이 마지막 라운드로 넘어갔다. 데제르비 감독은 자존심과 역사가 걸렸다고 했다.',
    briefing: '제이 해리스(디 애슬레틱) 보도다. 토트넘이 첼시에 2:1로 패하며 강등권 탈출이 마지막 라운드까지 넘어갔다. 데제르비 감독은 "강등을 피하는 것이 트로피를 드는 것보다 중요하다"고 밝히며 지난 시즌 유로파리그 우승을 언급했다. 클럽의 자존심과 역사가 걸린 싸움이라고 강조했다.',
    tweet: {
      author: 'Jay Harris / The Athletic',
      initials: 'JH',
      handle: '@jaydmharris',
      tier: 1,
      timeAgo: '2시간 전',
    },
    imageUrl: 'https://platform.cartilagefreecaptain.sbnation.com/wp-content/uploads/sites/60/2026/05/gettyimages-2277159165.jpg?quality=90&strip=all&crop=0%2C0.02516356316054%2C100%2C99.949672873679&w=2400',
    club: 'TOT',
    status: 'Opinion',
    hashtags: ['#토트넘', '#강등', '#데제르비'],
    reactions: 4100,
    comments: 2800,
    bookmarks: 445,
    shares: 223,
    voteFor: 38,
    voteAgainst: 62,
    voteForLabel: '잔류한다',
    voteAgainstLabel: '강등된다',
    participants: 2800,
    recentTrend: { pct: 8, direction: 'against', time: '30분' },
    debateQuestion: '마지막 라운드, 토트넘 강등 피할 수 있을까?',
    aiNarrative: '유러피언리그 우승팀이 강등권에서 마지막 라운드를 기다리게 됐다. 데제르비 감독 스스로 강등 위기를 인정한 셈이어서 팬들의 긴장감이 극에 달했다.',
    aiSummary: {
      for: ['마지막 라운드 상대 일정이 상대적으로 유리하다', '강등 회피 의지만큼은 역대급으로 높다', '데제르비 감독 체제에서 전술적 안정감 회복 조짐'],
      against: ['첼시에도 졌다 — 현재 폼으로는 불안하다', '감독 본인이 강등 위기를 사실상 인정했다', '유러피언리그 피로도가 시즌 내내 누적됐다'],
    },
    argumentPoints: [
      { id: 't1', text: '마지막 라운드 상대 일정이 토트넘에게 유리하다', stance: 'for', comments: 234 },
      { id: 't2', text: '이 폼으로 강등 피한다고? 현실적으로 힘들다', stance: 'against', comments: 312 },
      { id: 't3', text: '데제르비의 솔직한 발언이 오히려 팀을 단결시킬 수 있다', stance: 'neutral', comments: 156 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'TK', user: '@thfc_kr', club: 'TOT', timeAgo: '30분', text: '유로파 우승하고 강등이라니... 이게 말이 되는 상황이냐', likes: 1023, stance: 'against' },
      { id: 2, rank: '02', initials: 'SP', user: '@spurs_kr', club: 'TOT', timeAgo: '45분', text: '데제르비 솔직한 거 인정. 그냥 다 보여주는 스타일이잖아', likes: 734, stance: 'for' },
      { id: 3, rank: '03', initials: 'EK', user: '@epl_kr', timeAgo: '1시간', text: '마지막 라운드 상대가 누군지가 제일 중요하다. 확인해봐야 함', likes: 567 },
      { id: 4, rank: '04', initials: 'PL', user: '@prem_legacy', timeAgo: '1시간', text: '이 팀은 진짜 시즌 내내 롤러코스터였다. 마지막도 그렇게 끝나나', likes: 412, stance: 'against' },
    ],
  },

  // ── p19: 호날두 6번째 월드컵 오피셜 (sentimental / 중립) ─────────
  {
    id: 'p19',
    type: 'sentimental',
    title: '호날두, 6번째\n월드컵 출전 오피셜',
    summary: '2006년부터 2026년까지, 20년에 걸친 월드컵 여정. 마지막 무대에서 불태운다.',
    briefing: '파브리지오 로마노 보도다. 크리스티아누 호날두의 2026 북중미 월드컵 출전이 공식 확정됐다. 2006년 독일을 시작으로 2010, 2014, 2018, 2022에 이어 여섯 번째 무대다. 마지막이 될 가능성이 높은 이번 대회에서 어떤 활약을 펼칠지 전 세계의 관심이 쏠리고 있다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '14시간 전',
    },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Cristiano_Ronaldo_WC2022_-_01_%28cropped%29.jpg',
    status: 'Official',
    hashtags: ['#호날두', '#월드컵', '#6번째'],
    reactions: 24500,
    comments: 4800,
    bookmarks: 5600,
    shares: 3200,
    gradientFrom: '#1a0000',
    accentColor: '#ef4444',
    icon: '🇵🇹',
    comments_data: [
      { id: 1, rank: '01', initials: 'CR', user: '@cr7_kr', timeAgo: '30분', text: '6번이다. 진짜 괴물이 맞다. 이게 가능한 일이냐', likes: 7823 },
      { id: 2, rank: '02', initials: 'WC', user: '@worldcup_kr', timeAgo: '45분', text: '2006년 독일부터 봐온 사람으로서 이 순간이 너무 감동이다', likes: 5634 },
      { id: 3, rank: '03', initials: 'FK', user: '@football_kr', timeAgo: '1시간', text: '메시는 은퇴하고 호날두는 6번째 월드컵. 이 시대 마지막 목격자가 된 기분', likes: 4291 },
      { id: 4, rank: '04', initials: 'BR', user: '@brazil_kr', timeAgo: '1시간', text: '제발 이번엔 우승 한 번만. 마지막이잖아', likes: 3156 },
    ],
  },

  // ── p1: 카세미루 이별 오피셜 (debate / MUN) ─────────────────────
  {
    id: 'p1',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '카세미루,\n맨유와 이별 오피셜',
    summary: '맨유와 공식 이별. 경기 후 기자회견은 감정적 이유로 열리지 않았다.',
    briefing: '새뮤얼 럭허스트 보도다. 카세미루가 맨유를 공식적으로 떠난다. 경기 후 기자회견이 예정됐지만 "너무 감정적인 상황"을 이유로 취소됐다. 높은 연봉을 받는 동안에도 팬들과의 유대만큼은 진심이었다는 평가가 나오고 있다.',
    tweet: {
      author: 'Samuel Luckhurst',
      initials: 'SL',
      handle: '@samuelluckhurst',
      tier: 2,
      timeAgo: '11시간 전',
    },
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9V2M9drksopVGFPxNhAZxDOHMO8U0Pm5i3w&s',
    club: 'MUN',
    status: 'Official',
    hashtags: ['#카세미루', '#맨유', '#이별'],
    reactions: 3200,
    comments: 1890,
    bookmarks: 421,
    shares: 134,
    voteFor: 35,
    voteAgainst: 65,
    voteForLabel: '성공한 영입',
    voteAgainstLabel: '실패한 영입',
    participants: 1890,
    recentTrend: { pct: 5, direction: 'against', time: '30분' },
    debateQuestion: '카세미루 영입, 성공이었나 실패였나?',
    aiNarrative: '트로피도 들었고 마지막 시즌도 임팩트가 있었다. 하지만 가운데 2~3시즌의 성적과 연봉을 생각하면 의문이 남는다.',
    aiSummary: {
      for: ['첫 시즌 수비 안정감 확실', '리그컵 우승 기여', '마지막 시즌도 존재감 강했다', '팬들과의 유대감은 진짜였다'],
      against: ['중간 시즌 퍼포먼스 하락이 뼈아팠다', '연봉 대비 총 기여도 의문', '그 돈이면 더 좋은 선택 가능했다'],
    },
    argumentPoints: [
      { id: 'a1', text: '첫 시즌 + 마지막 시즌은 레전드급 퍼포먼스', stance: 'for', comments: 182 },
      { id: 'a2', text: '중간 시즌들이 너무 실망스러웠다', stance: 'against', comments: 241 },
      { id: 'a3', text: '눈물의 이별 — 팬과의 유대는 진짜였다', stance: 'neutral', comments: 92 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'RC', user: '@redcafe_88', club: 'MUN', timeAgo: '2시간', text: '맨유 팬 입장에서는 그냥 실패다. 1억 쓰고 중간 3시즌 버렸잖아', likes: 723, stance: 'against' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_history', club: 'MUN', timeAgo: '3시간', text: '첫 시즌은 진짜 좋았다. 리그컵 들었고. 문제는 그 이후였지', likes: 512, stance: 'for' },
      { id: 3, rank: '03', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '4시간', text: '감정적이라 기자회견 못 했다는 게 오히려 더 사람 같아 보임', likes: 389 },
      { id: 4, rank: '04', initials: 'MK', user: '@mancunian_kr', club: 'MUN', timeAgo: '5시간', text: '이번 시즌 카세미루 없을 때 팀이 얼마나 흔들렸는지 봤잖아. 그게 다야', likes: 234, stance: 'for' },
    ],
  },

  // ── p7: 하베르츠 결승골 / 아스날 우승 (today_debate / ARS) ───────
  {
    id: 'p7',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '하베르츠 결승골,\n아스날 우승 가능?',
    summary: '번리전 1-0 승리로 우승까지 3점 차. 마지막 라운드에서 결판난다.',
    briefing: 'Sky Sports 보도다. 하베르츠의 결승골로 아스날이 번리를 1-0으로 꺾었다. 이로써 리그 선두와의 격차는 3점으로 줄었고, 마지막 라운드 경쟁팀 결과에 따라 2004~05 시즌 이후 첫 우승이 확정될 수 있다.',
    tweet: {
      author: 'Sky Sports Premier League',
      initials: 'SS',
      handle: '@SkySports',
      tier: 1,
      timeAgo: '8시간 전',
    },
    imageUrl: 'https://www.fbcnews.com.fj/wp-content/uploads/2024/10/harvez.jpg',
    club: 'ARS',
    status: 'Opinion',
    hashtags: ['#아스날', '#하베르츠', '#EPL우승'],
    reactions: 5600,
    comments: 3100,
    bookmarks: 789,
    shares: 445,
    voteFor: 54,
    voteAgainst: 46,
    voteForLabel: '우승 가능',
    voteAgainstLabel: '또 무너진다',
    participants: 3100,
    recentTrend: { pct: 4, direction: 'for', time: '30분' },
    debateQuestion: '아스날, 이번 시즌 마침내 우승할 수 있을까?',
    aiNarrative: '마지막 라운드, 단 3점 차. 하베르츠의 결승골로 희망을 이어갔다. 하지만 역사는 반복되는가 — 아스날은 또 무너질 것인가?',
    aiSummary: {
      for: ['현재 폼이 시즌 내내 최고 수준', '하베르츠의 결정력이 살아났다', '이번엔 다르다, 경험이 쌓였다'],
      against: ['마지막 라운드에서 아스날은 항상 무너진다', '선두는 3점 차 이상이 필요했다', '아르테타의 빅게임 운영이 여전히 걱정'],
    },
    argumentPoints: [
      { id: 'f1', text: '하베르츠, 이번 시즌 가장 중요한 골맨', stance: 'for', comments: 267 },
      { id: 'f2', text: '아스날은 타이틀 레이스마다 흔들렸다', stance: 'against', comments: 334 },
      { id: 'f3', text: '마지막 라운드 상대팀 일정이 관건', stance: 'neutral', comments: 198 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '1시간', text: '이번엔 진짜 된다. 하베르츠 폼 보라', likes: 1234, stance: 'for' },
      { id: 2, rank: '02', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '1시간', text: '16-17 이후 너무 오래됐다... 제발 이번엔', likes: 987, stance: 'for' },
      { id: 3, rank: '03', initials: 'EK', user: '@epl_kr', club: 'ARS', timeAgo: '2시간', text: '아스날 팬이지만 솔직히 마지막 라운드 믿음이 안 간다', likes: 756, stance: 'against' },
      { id: 4, rank: '04', initials: 'PL', user: '@prem_legacy', timeAgo: '2시간', text: '상대팀 일정 봐야지. 섣불리 판단 이르다', likes: 543 },
    ],
  },

  // ── p2: 칸셀루 바르사 잔류? (debate / MCI) ─────────────────────
  {
    id: 'p2',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '칸셀루, 바르사 잔류?\n사우디 복귀?',
    summary: '알 힐랄 임대 종료 후 거취 협상 중. 플리크 감독은 잔류를 원한다.',
    briefing: '파브리지오 로마노 보도다. 알 힐랄에서 임대 온 칸셀루의 잔류를 놓고 바르셀로나가 협상 중이다. 플리크 감독은 "칸셀루가 우리에게 무엇을 줬는지 모두 안다"며 강하게 잔류를 희망했다. 바르사가 영구 이적료를 감당할 수 있을지가 관건이다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '5시간 전',
    },
    imageUrl: 'https://www.fcbarcelona.com/fcbarcelona/photo/2023/09/25/08593578-2837-4af2-9235-e3a56e3db23c/2023-09-16_FCBvsBETIS_97.jpg',
    club: 'MCI',
    status: 'Talks',
    hashtags: ['#칸셀루', '#바르셀로나', '#사우디'],
    reactions: 2800,
    comments: 1540,
    bookmarks: 312,
    shares: 98,
    voteFor: 74,
    voteAgainst: 26,
    voteForLabel: '바르사 잔류',
    voteAgainstLabel: '사우디 복귀',
    participants: 1540,
    recentTrend: { pct: 6, direction: 'for', time: '1시간' },
    debateQuestion: '칸셀루, 바르사에 남아야 할까? 사우디로 돌아가야 할까?',
    aiNarrative: '알 힐랄에서 임대 온 칸셀루는 플리크 체제에서 완전히 살아났다. 하지만 바르사의 재정 불안과 알 힐랄의 복귀 요청이 걸림돌이다.',
    aiSummary: {
      for: ['플리크 체제에서 이번 시즌 커리어 최고폼', '바르셀로나 전술에 완벽히 최적화됨', '사우디 복귀는 커리어 사실상 종료'],
      against: ['알 힐랄 임대 계약 조건상 복귀 압박', '바르사 재정 불안 — 영구 계약은 불투명', '챔피언스리그 출전이 더 이상 보장 아님'],
    },
    argumentPoints: [
      { id: 'b1', text: '플리크 체제에서 커리어 최고폼 중', stance: 'for', comments: 198 },
      { id: 'b2', text: '사우디 복귀는 커리어 사실상 종료', stance: 'for', comments: 154 },
      { id: 'b3', text: '바르사 재정 불안 — 잔류 보장 없다', stance: 'against', comments: 211 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BF', user: '@barca_fan_kr', club: 'MCI', timeAgo: '1시간', text: '이번 시즌 칸셀루 없었으면 챔스 어땠을지... 무조건 잔류', likes: 634, stance: 'for' },
      { id: 2, rank: '02', initials: 'PL', user: '@prem_legacy', club: 'MCI', timeAgo: '2시간', text: '사우디 가면 커리어 끝나는 거다. 플리크 믿고 가야지', likes: 445, stance: 'for' },
      { id: 3, rank: '03', initials: 'FK', user: '@football_kr', club: 'MCI', timeAgo: '3시간', text: '알 힐랄이 복귀 원하는 이상 바르사가 돈 내야 하는데 과연 가능한가', likes: 267, stance: 'against' },
    ],
  },

  // ── p13: 야말 월드컵 첫경기 결장 (today_debate / ARS) ───────────
  {
    id: 'p13',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '야말, 월드컵 첫경기\n결장 가능성 제기',
    summary: '훈련 중 부상으로 개막전 출전이 불투명해졌다.',
    briefing: '파브리지오 로마노 단독 보도다. 야말이 훈련 중 충격을 입어 스페인 월드컵 개막전 출전 여부가 불투명해졌다. 의료팀이 상황을 면밀히 점검 중이며, 아직 최종 결정은 내려지지 않은 상태다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '30분 전',
    },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Lamine_Yamal_in_2025.jpg',
    club: 'ARS',
    status: 'Opinion',
    hashtags: ['#야말', '#스페인', '#월드컵'],
    reactions: 4200,
    comments: 2700,
    bookmarks: 567,
    shares: 334,
    voteFor: 67,
    voteAgainst: 33,
    voteForLabel: '없어도 이긴다',
    voteAgainstLabel: '야말 필수',
    participants: 2700,
    recentTrend: { pct: 5, direction: 'for', time: '30분' },
    debateQuestion: '야말 없이 스페인 첫 경기, 승리할 수 있을까?',
    aiNarrative: '야말이 없어도 이기는 팀이라는 평가와, 야말이 없으면 스페인 공격의 창의성 자체가 사라진다는 우려가 팽팽히 맞선다.',
    aiSummary: {
      for: ['스페인 스쿼드 뎁스는 세계 최고 수준', '조별 첫 경기 상대 전력이 강하지 않다', '무리하지 않고 보호하는 게 장기적으로 맞다'],
      against: ['야말 없는 스페인 공격은 예측 불가능성을 잃는다', '유로 때처럼 야말이 바꾸는 판이 있다', '첫 경기 리듬이 토너먼트 전체에 영향'],
    },
    argumentPoints: [
      { id: 'y1', text: '페드리·모라타 있으면 첫 경기 충분히 이긴다', stance: 'for', comments: 312 },
      { id: 'y2', text: '야말의 드리블·돌파는 대체 불가', stance: 'against', comments: 289 },
      { id: 'y3', text: '첫경기 무리시키느니 2라운드부터 투입이 맞다', stance: 'neutral', comments: 201 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'SP', user: '@spain_kr', timeAgo: '15분', text: '스페인이 야말 하나 없다고 못 이기는 팀이냐. 뎁스가 얼만데', likes: 934, stance: 'for' },
      { id: 2, rank: '02', initials: 'BF', user: '@barca_fan_kr', timeAgo: '20분', text: '야말 없는 스페인 왼쪽은 진짜 다르다. 과소평가하지 마라', likes: 756, stance: 'against' },
      { id: 3, rank: '03', initials: 'WC', user: '@worldcup_kr', timeAgo: '25분', text: '첫경기 무리시키다가 다치면 어쩌려고. 그냥 2라운드부터 써라', likes: 612, stance: 'for' },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '30분', text: '유로 결승 야말 그 장면 생각하면... 제발 건강하게 나와줬으면', likes: 489 },
    ],
  },

  // ── p3: 브루노 20어시 달성 (today_debate / MUN) ─────────────────
  {
    id: 'p3',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '브루노 20어시 달성,\n마지막 라운드 기록 경신?',
    summary: '앙리·데 브라이너와 EPL 역대 타이기록. 마지막 1경기가 남았다.',
    briefing: '사이먼 스톤 보도다. 브루노 페르난데스가 20어시스트를 기록하며 티에리 앙리, 케빈 데 브라이너와 EPL 역대 타이기록을 달성했다. 브루노 본인은 "19개 됐을 때 생각이 들기 시작했다"고 밝혔다. 마지막 라운드 단 1경기에서 단독 신기록을 쓸 수 있다.',
    tweet: {
      author: 'Simon Stone',
      initials: 'SS',
      handle: '@sistoney67',
      tier: 2,
      timeAgo: '1시간 전',
    },
    imageUrl: 'https://static.independent.co.uk/2026/05/17/14/2276701105..',
    club: 'MUN',
    status: 'Opinion',
    hashtags: ['#브루노', '#어시스트기록', '#EPL역사'],
    reactions: 4100,
    comments: 2890,
    bookmarks: 678,
    shares: 312,
    voteFor: 61,
    voteAgainst: 39,
    voteForLabel: '21어시 신기록',
    voteAgainstLabel: '20어시 마감',
    participants: 2890,
    recentTrend: { pct: 8, direction: 'for', time: '30분' },
    debateQuestion: '마지막 라운드, 브루노 21어시 신기록 달성 가능?',
    aiNarrative: '단 1라운드 남았다. 앙리·데 브라이너와 어깨를 나란히 한 브루노 — 역사를 다시 쓸 수 있을까?',
    aiSummary: {
      for: ['현재 폼이 시즌 내내 최고 수준 유지', '마지막 경기 강력한 동기부여 확실', '이미 심리적 장벽을 넘은 상태'],
      against: ['상대팀이 집중 견제할 게 뻔하다', '단 1경기에서 어시스트 보장 없음', '팀 전술적 필요에 따라 달라질 수도'],
    },
    argumentPoints: [
      { id: 'c1', text: '현재 폼이면 21어시 충분히 가능', stance: 'for', comments: 312 },
      { id: 'c2', text: '상대팀 집중 견제가 변수', stance: 'against', comments: 278 },
      { id: 'c3', text: '20어시 자체가 이미 역사적 기록', stance: 'neutral', comments: 145 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BK', user: '@brunokr_fan', club: 'MUN', timeAgo: '30분', text: '앙리급 시즌이다. 21개 간다', likes: 1023, stance: 'for' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_numbers', club: 'MUN', timeAgo: '45분', text: '상대팀이 집중 마크할 텐데... 쉽지 않다', likes: 756, stance: 'against' },
      { id: 3, rank: '03', initials: 'MF', user: '@midfield_kr', club: 'MUN', timeAgo: '1시간', text: '20어시도 역대급인데 21까지? 이 세대 최고의 미드필더', likes: 534, stance: 'for' },
      { id: 4, rank: '04', initials: 'RC', user: '@redcafe_88', club: 'MUN', timeAgo: '1시간', text: '이 선수 팔자고? 기록 보고도 매각설 나오면 진짜 ㅋㅋ', likes: 445 },
    ],
  },

  // ── p5: 네이마르 눈물의 월드컵 발탁 (debate / 중립) ─────────────
  {
    id: 'p5',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '네이마르, 눈물의\n월드컵 발탁',
    summary: '2년 넘는 부상 공백을 딛고 안첼로티 감독의 브라질 월드컵 명단에 이름을 올렸다.',
    briefing: '디 애슬레틱 보도다. 안첼로티 감독이 2년 넘게 부상으로 이탈했던 34세 네이마르를 브라질 월드컵 최종 명단에 포함시켰다. 반면 이번 시즌 첼시에서 활약하던 주앙 페드루는 명단에서 빠졌다. 34세 네이마르에게 이번이 마지막 월드컵 무대가 될 가능성이 높다.',
    tweet: {
      author: 'The Athletic | Football',
      initials: 'TA',
      handle: '@TheAthletic',
      tier: 1,
      timeAgo: '7시간 전',
    },
    imageUrl: 'https://images.ctfassets.net/3mv54pzvptwz/55YLwKPDnRXkqMBITRpWbC/0c2aefc04afa455c20e9ca0d209698e0/53174188191_42d4c831ae_o.jpg',
    status: 'Official',
    hashtags: ['#네이마르', '#브라질', '#월드컵'],
    reactions: 4800,
    comments: 3200,
    bookmarks: 620,
    shares: 289,
    voteFor: 31,
    voteAgainst: 69,
    voteForLabel: '네이마르 필요해',
    voteAgainstLabel: '세대교체해야',
    participants: 3200,
    recentTrend: { pct: 9, direction: 'against', time: '1시간' },
    debateQuestion: '2년의 공백을 딛고 돌아온 네이마르, 브라질 월드컵 엔트리에 포함되어야 할까?',
    aiNarrative: '2년 넘게 부상으로 사라졌던 34살이 안첼로티의 손에 이끌려 돌아왔다. 마지막 무대를 향한 간절함과, 주앙 페드로 같은 젊은 피를 원하는 여론이 충돌하고 있다.',
    aiSummary: {
      for: ['2년 공백을 이겨낸 것 자체가 이미 기적', '큰 무대 경험은 아직 아무도 못 따라온다', '안첼로티가 직접 폼을 확인하고 내린 결정'],
      against: ['주앙 페드로를 포함시켰어야 했다', '부상 재발 리스크가 너무 높다', '34살에 월드컵 강도를 버틸 수 있을지 의문'],
    },
    argumentPoints: [
      { id: 'n1', text: '2년 공백 극복 — 의지만큼은 역대급', stance: 'for', comments: 289 },
      { id: 'n2', text: '주앙 페드로 탈락은 납득 불가', stance: 'against', comments: 412 },
      { id: 'n3', text: '부상 재발 시 팀 전체에 리스크', stance: 'against', comments: 356 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BR', user: '@brazil_kr', timeAgo: '2시간', text: '2년을 이겨내고 돌아왔다는 것 자체가 감동이지. 응원할 수밖에', likes: 892, stance: 'for' },
      { id: 2, rank: '02', initials: 'JK', user: '@joaopedro_fan', timeAgo: '3시간', text: '주앙 페드로 팬으로서 진짜 납득이 안 감. 첼시에서 활약 중인데', likes: 734, stance: 'against' },
      { id: 3, rank: '03', initials: 'WC', user: '@worldcup_kr', timeAgo: '4시간', text: '카타르도 부상으로 나갔잖아. 이번엔 제발 버텨줬으면', likes: 521, stance: 'for' },
      { id: 4, rank: '04', initials: 'FK', user: '@football_kr', timeAgo: '5시간', text: '진짜 마지막 무대라는 거 알고 있을 텐데... 눈물날 것 같다', likes: 412 },
    ],
  },

  // ── p14: 알론소 첼시 감독 오피셜 (debate / CHE) ─────────────────
  {
    id: 'p14',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '알론소, 첼시 감독\n오피셜 확정',
    summary: '다비드 오른스타인 단독 보도. 4년 계약 완료, 공식 발표 임박.',
    briefing: '다비드 오른스타인 단독 보도다. 하비 알론소가 첼시 감독직에 합류하기로 최종 합의했다. 지난주 초 런던을 직접 방문해 계약을 확정지었으며 4년 계약이 완료됐다. 첼시의 1순위 목표였고, 알론소 본인도 스탬포드 브릿지행을 원했다는 전언이다.',
    imageUrl: 'https://images2.minutemediacdn.com/image/upload/c_crop,x_0,y_0,w_1919,h_1079/c_fill,w_720,ar_16:9,f_auto,q_auto,g_auto/images/voltaxMediaLibrary/mmsport/si/01krtk3v16vszp5dee2e.jpg',
    tweet: {
      author: 'David Ornstein',
      initials: 'DO',
      handle: '@David_Ornstein',
      tier: 1,
      timeAgo: '2일 전',
    },
    club: 'CHE',
    status: 'Official',
    hashtags: ['#알론소', '#첼시', '#신임감독'],
    reactions: 5100,
    comments: 3400,
    bookmarks: 712,
    shares: 389,
    voteFor: 58,
    voteAgainst: 42,
    voteForLabel: '성공한다',
    voteAgainstLabel: '실패한다',
    participants: 3400,
    recentTrend: { pct: 6, direction: 'for', time: '1시간' },
    debateQuestion: '알론소, 첼시에서도 레버쿠젠의 기적을 재현할 수 있을까?',
    aiNarrative: '레버쿠젠 불패 시즌으로 세계 최고 감독 반열에 오른 알론소. 하지만 레알 마드리드에서의 기대 이하 성과가 남긴 물음표와, 첼시 특유의 구단 문화가 변수로 떠오르고 있다.',
    aiSummary: {
      for: ['레버쿠젠 불패 시즌 — 전술 능력은 이미 세계 최고급 검증', '첼시 스쿼드 뎁스라면 전술 구현 충분히 가능', '4년 장기 계약 — 구단이 완전한 신뢰를 보냈다'],
      against: ['레알 마드리드에서의 성과가 기대에 미치지 못했다', '첼시는 감독을 갈아치우는 구단 문화로 유명하다', 'PL은 분데스리가와 강도 자체가 다르다'],
    },
    argumentPoints: [
      { id: 'xa1', text: '레버쿠젠 불패 — 전술 천재임은 이미 증명', stance: 'for', comments: 423 },
      { id: 'xa2', text: '레알 이후 커리어에 물음표가 남았다', stance: 'against', comments: 356 },
      { id: 'xa3', text: '첼시 구단주가 또 감독 자를 수도 있다', stance: 'against', comments: 289 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'CF', user: '@chelsea_fan_kr', club: 'CHE', timeAgo: '1시간', text: '레버쿠젠 때 봤잖아. 믿어보자. 이번엔 진짜 제대로 된 감독 왔다', likes: 1123, stance: 'for' },
      { id: 2, rank: '02', initials: 'BL', user: '@blue_london', club: 'CHE', timeAgo: '1시간', text: '첼시가 감독 4시즌 내보낸 거 알론소도 알 텐데... 각오하고 온 거겠지', likes: 867, stance: 'against' },
      { id: 3, rank: '03', initials: 'EK', user: '@epl_kr', timeAgo: '2시간', text: '레알에서 흔들린 게 좀 걸린다. PL은 진짜 다른 리그인데', likes: 654, stance: 'against' },
      { id: 4, rank: '04', initials: 'PL', user: '@prem_legacy', timeAgo: '2시간', text: '4년 계약이 포인트다. 구단이 진짜 오래 가져가겠다는 신호', likes: 512, stance: 'for' },
    ],
  },

  // ── p4: 캐릭 맨유 감독 거피셜 (debate / MUN) ────────────────────
  {
    id: 'p4',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '캐릭 맨유 감독 거피셜,\n내년 시즌 성공할까?',
    summary: '파브리지오 로마노 거피셜. 이사회 협상 막바지, 발표 임박.',
    briefing: '파브리지오 로마노 보도다. 마이클 캐릭이 맨유 감독직에 내정됐다. 이사회와의 협상이 막바지에 접어들었으며, 공식 발표가 곧 이뤄질 전망이다. 미들즈브러에서 감독 경험을 쌓은 클럽 레전드가 시즌 리빌딩을 이끌 예정이다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '3시간 전',
    },
    imageUrl: 'https://i2-prod.manchestereveningnews.co.uk/article33961719.ece/ALTERNATES/s1200f/0_GettyImages-2276137385.jpg',
    club: 'MUN',
    status: 'Advanced',
    hashtags: ['#캐릭', '#맨유감독', '#리빌딩'],
    reactions: 2900,
    comments: 2100,
    bookmarks: 445,
    shares: 167,
    voteFor: 44,
    voteAgainst: 56,
    voteForLabel: '성공 가능',
    voteAgainstLabel: '회의적',
    participants: 2100,
    recentTrend: { pct: 3, direction: 'against', time: '1시간' },
    debateQuestion: '캐릭 감독 체제, 내년 시즌 성공할 수 있을까?',
    aiNarrative: '클럽 레전드가 감독직에 오른다. 경험 부족을 우려하는 시각과, 맨유 DNA를 아는 적임자라는 기대가 충돌 중이다.',
    aiSummary: {
      for: ['맨유 클럽 문화를 누구보다 잘 이해', '선수들과의 유대관계 이미 형성됨', '미들즈브러 감독직 현장 경험 보유'],
      against: ['최고 수준 감독 경력 전무', '리빌딩 상황에선 검증된 감독 필요', '전술적 유연성 아직 검증 안 됨'],
    },
    argumentPoints: [
      { id: 'd1', text: '맨유 DNA를 아는 감독이 필요한 시점', stance: 'for', comments: 267 },
      { id: 'd2', text: '최고 수준 감독 경력이 전무하다', stance: 'against', comments: 334 },
      { id: 'd3', text: '이적시장 보강이 성패를 가른다', stance: 'neutral', comments: 189 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '30분', text: '레전드가 맡는 건 좋은데 지금이 타이밍이 맞나? 경험이 너무 부족해', likes: 834, stance: 'against' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_history', club: 'MUN', timeAgo: '1시간', text: '일단 믿어보자. 맨유를 누구보다 잘 아는 사람이잖아', likes: 567, stance: 'for' },
      { id: 3, rank: '03', initials: 'SA', user: '@sir_alex_', club: 'MUN', timeAgo: '1시간', text: '전술 스태프 잘 꾸리면 가능하다. 퍼거슨도 처음엔 의심받았음', likes: 412, stance: 'for' },
      { id: 4, rank: '04', initials: 'MK', user: '@mancunian_kr', club: 'MUN', timeAgo: '2시간', text: '이적시장 뭘 데려오느냐에 달려있다. 감독 혼자서는 답 없음', likes: 298 },
    ],
  },

  // ── p6: 펩 과르디올라 맨시티 이별 (sentimental / MCI) ───────────
  {
    id: 'p6',
    type: 'sentimental',
    title: '펩 과르디올라,\n맨시티와 이별',
    summary: '9년간 리그 6회 우승에 챔스까지. 올여름 에티하드를 떠난다.',
    briefing: '파브리지오 로마노 보도다. 펩 과르디올라가 맨시티를 떠나기로 결정했다. 리그 6회 우승에 챔피언스리그 우승까지 이끈 역대급 감독이 올여름 에티하드를 떠난다. 후임 감독으로는 엔조 마레스카가 유력하게 거론되고 있다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '6시간 전',
    },
    imageUrl: 'https://i2-prod.liverpool.com/article33969458.ece/ALTERNATES/s1023/0_GettyImages-2276556390.jpg',
    club: 'MCI',
    status: 'Official',
    hashtags: ['#펩과르디올라', '#맨시티', '#이별'],
    reactions: 12400,
    comments: 2890,
    bookmarks: 1890,
    shares: 789,
    gradientFrom: '#001a38',
    accentColor: '#6dc1e7',
    icon: '🔵',
    comments_data: [
      { id: 1, rank: '01', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '30분', text: '9년간 감사했습니다. 역사상 최고의 감독이었습니다', likes: 4231 },
      { id: 2, rank: '02', initials: 'BL', user: '@blue_legacy', club: 'MCI', timeAgo: '45분', text: '제발 1년만 더... 마지막으로 챔스 한 번만', likes: 3456 },
      { id: 3, rank: '03', initials: 'GG', user: '@guardiola_way', club: 'MCI', timeAgo: '1시간', text: '펩 없는 맨시티는 상상이 안 된다. 한 시대가 진짜 끝났다', likes: 2891 },
      { id: 4, rank: '04', initials: 'EM', user: '@etihad_memories', club: 'MCI', timeAgo: '1시간', text: '마르체스카가 후임이라고? 펩 그림자가 너무 크다', likes: 1823 },
    ],
  },

  // ── p15: 아르테타 "본머스 팬" (general / ARS) ────────────────────
  {
    id: 'p15',
    type: 'general',
    title: '아르테타 "나는 본머스의\n팬이 될 것"',
    summary: '오늘 밤 맨시티가 지면 우승 확정. 아르테타는 TV 앞에서 본머스를 응원할 준비가 됐다.',
    briefing: 'Sky Sports 보도다. 아르테타 감독이 "내 생애 가장 열성적인 본머스 팬이 될 것"이라고 말했다. 오늘 밤 맨시티가 본머스에게 발목이 잡히면 아스날이 우승을 확정 짓는다. 아스날 팬들의 시선이 에티하드가 아닌 바이털리티 스타디움으로 쏠리고 있다.',
    tweet: {
      author: 'Sky Sports News',
      initials: 'SS',
      handle: '@SkySportsNews',
      tier: 1,
      timeAgo: '27분 전',
    },
    imageUrl: 'https://external-preview.redd.it/every-word-from-artetas-post-chelsea-presser-v0-LojAaY1XjGgAi2q7hx0s_g_GDsJoTIr1vchJdEkSyGU.jpeg?auto=webp&s=f5f1dd7e77ba680e07c67ed1fa139f030ad4533d',
    club: 'ARS',
    status: 'Opinion',
    hashtags: ['#아르테타', '#아스날', '#우승'],
    reactions: 8900,
    comments: 1240,
    bookmarks: 567,
    shares: 445,
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '5분', text: '아르테타 ㅋㅋㅋ 본머스 응원한다고 ㅋㅋ 제발 이번엔 진짜로', likes: 2341 },
      { id: 2, rank: '02', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '10분', text: '본머스야 제발... 아스날 팬 전체가 너희를 응원한다', likes: 1987 },
      { id: 3, rank: '03', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '15분', text: '걱정 마라. 맨시티가 알아서 이긴다 ㅋㅋ', likes: 1123 },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '20분', text: '이 발언 자체가 화제다. 아르테타도 긴장 많이 되는 거지', likes: 876 },
    ],
  },

  // ── p10: 마레스카 맨시티 차기 감독 (debate / MCI) ───────────────
  {
    id: 'p10',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '마레스카, 펩 후임으로\n맨시티 유력 감독 후보',
    summary: '첼시를 챔스까지 이끈 마레스카가 펩 후임 1순위로 거론되고 있다.',
    briefing: '파브리지오 로마노 보도다. 맨시티가 엔조 마레스카를 차기 감독 1순위로 검토하고 있다. 현재 접촉이 진행 중이며, 구단 측은 "프로젝트를 이어갈 수 있다"고 판단 중이다. 마레스카는 올 시즌 첼시를 챔피언스리그 준결승까지 이끌며 전술 능력을 증명했다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      timeAgo: '4시간 전',
    },
    imageUrl: 'https://i.namu.wiki/i/D8ly0WWiB7_sWgztlLCUVlc7xR51rD_4JKhSvo1XyuzlQQbXeR8OAJcUYuLf4Nuyun2INsx8Qc_kZf1Rvyr8eg.webp',
    club: 'MCI',
    status: 'Advanced',
    hashtags: ['#마레스카', '#맨시티', '#차기감독'],
    reactions: 2600,
    comments: 1780,
    bookmarks: 389,
    shares: 112,
    voteFor: 42,
    voteAgainst: 58,
    voteForLabel: '성공한다',
    voteAgainstLabel: '실패한다',
    participants: 1780,
    recentTrend: { pct: 7, direction: 'against', time: '1시간' },
    debateQuestion: '마레스카, 펩 없는 맨시티에서 성공할 수 있을까?',
    aiNarrative: '첼시에서 챔피언스리그까지 이끌며 전술적 능력을 증명한 마레스카. 하지만 펩의 그림자가 드리운 에티하드에서의 압박은 차원이 다르다.',
    aiSummary: {
      for: ['첼시 체제에서 전술 구현 능력 이미 증명', '맨시티 스쿼드 퀄리티가 워낙 높아 초반 완충 가능', '젊은 감독 특유의 적응력과 유연성'],
      against: ['펩 후임이라는 심리적 압박은 상상 이상', '챔스 우승 경험 없는 감독에게 맨시티 팬들은 냉정', '에티하드 드레싱룸 장악은 전혀 다른 문제'],
    },
    argumentPoints: [
      { id: 'm1', text: '첼시 챔스 준결승 진출 — 전술 능력 증명 완료', stance: 'for', comments: 245 },
      { id: 'm2', text: '펩 그림자가 너무 크다 — 누가 와도 힘들다', stance: 'against', comments: 312 },
      { id: 'm3', text: '스쿼드 퀄리티가 감독을 커버해줄 것', stance: 'neutral', comments: 178 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '1시간', text: '첼시에서 그 선수들로 챔스 간 거잖아. 능력은 있다', likes: 678, stance: 'for' },
      { id: 2, rank: '02', initials: 'BL', user: '@blue_legacy', club: 'MCI', timeAgo: '2시간', text: '펩 후임이면 누구든 지옥이다. 마레스카 불쌍하다', likes: 534, stance: 'against' },
      { id: 3, rank: '03', initials: 'EM', user: '@etihad_memories', club: 'MCI', timeAgo: '2시간', text: '이미 첼시에서 증명했잖아. 맨시티 스쿼드면 더 잘하겠지', likes: 389, stance: 'for' },
      { id: 4, rank: '04', initials: 'GG', user: '@guardiola_way', club: 'MCI', timeAgo: '3시간', text: '뭘 해도 "펩 같았으면..."이라는 말 들을 건데. 힘든 자리다', likes: 267 },
    ],
  },

  // ── p11: 무리뉴 래시포드 재결합 (general / MUN) ─────────────────
  {
    id: 'p11',
    type: 'general',
    title: '무리뉴, 래시포드\n재결합 원한다는 루머',
    summary: '바르사 임대 종료 후 거취 미정. 무리뉴가 올여름 영입에 관심을 보이고 있다는 현지 보도.',
    briefing: '벤 제이콥스 보도다. 무리뉴 감독이 올여름 래시포드 영입에 관심을 보이고 있다. 바르셀로나 임대가 종료되는 래시포드의 거취는 아직 확정되지 않은 상태다. 페네르바체가 영입을 검토 중인 것으로 알려졌다.',
    tweet: {
      author: 'Ben Jacobs',
      initials: 'BJ',
      handle: '@JacobsBen',
      tier: 2,
      timeAgo: '3시간 전',
    },
    imageUrl: 'https://vstatic.vietnam.vn/vietnam/resource/IMAGE/2026/05/16/1778934497483_2084811_43691430_2560_1440.jpeg',
    club: 'MUN',
    status: 'Rumour',
    hashtags: ['#래시포드', '#무리뉴', '#페네르바체'],
    reactions: 2100,
    comments: 1340,
    bookmarks: 234,
    shares: 89,
    comments_data: [
      { id: 1, rank: '01', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '40분', text: '맨유 팬으로서 그냥 다시는 못 볼 것 같다는 생각이 드는 게 슬프다', likes: 712 },
      { id: 2, rank: '02', initials: 'BF', user: '@barca_fan_kr', timeAgo: '1시간', text: '바르사도 연장 생각 없다던데. 그냥 터키 가는 거 아닌가', likes: 523 },
      { id: 3, rank: '03', initials: 'RM', user: '@realmadrid_kr', timeAgo: '1시간', text: '무리뉴 밑에서 다시 기회 받으면 살아날 수도 있지 않나', likes: 401 },
      { id: 4, rank: '04', initials: 'MK', user: '@mancunian_kr', club: 'MUN', timeAgo: '2시간', text: '맨유에서 저 꼴 보고도 무리뉴가 원한다고? 이해가 안 됨', likes: 334 },
    ],
  },

  // ── p12: PGMO 오심 인정 (general / MUN) ─────────────────────────
  {
    id: 'p12',
    type: 'general',
    title: 'PGMO, 맨유전 쿠냐 골\n음뵈모 핸드볼 오심 인정',
    summary: 'PGMO가 음뵈모 핸드볼 오심을 공식 인정했다. 결과는 그대로 유지된다.',
    briefing: '맨유 공식 성명이다. PGMO가 노팅엄 포레스트전 쿠냐 득점 과정에서 음뵈모의 핸드볼 반칙을 잡지 못한 것을 "중대한 오심"으로 공식 인정했다. VAR도 이를 바로잡지 못했다. 하지만 경기 결과는 변경되지 않는다.',
    tweet: {
      author: 'Manchester United',
      initials: 'MU',
      handle: '@ManUtd',
      tier: 1,
      timeAgo: '2시간 전',
    },
    imageUrl: 'https://www.sportschosun.com/article/html/2026/05/19/2026051901001094100072481_w.jpg',
    club: 'MUN',
    status: 'Official',
    hashtags: ['#오심', '#PGMO', '#맨유'],
    reactions: 3400,
    comments: 2100,
    bookmarks: 312,
    shares: 198,
    comments_data: [
      { id: 1, rank: '01', initials: 'RC', user: '@redcafe_88', club: 'MUN', timeAgo: '20분', text: '인정은 해주는데 결과는 안 바꿔줌 ㅋㅋㅋ 이게 무슨 의미가 있냐', likes: 1234 },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_history', club: 'MUN', timeAgo: '35분', text: 'VAR 뭐하냐 진짜. 저게 핸드볼 못 잡으면 뭘 잡는 거냐', likes: 987 },
      { id: 3, rank: '03', initials: 'SA', user: '@sir_alex_', club: 'MUN', timeAgo: '45분', text: '맨유한테는 왜 이런 게 항상 이렇게 많냐. 음모론 아님 그냥 통계다', likes: 756 },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '1시간', text: '인정하면 뭐하나. 승점은 안 돌려주잖아. 매번 이 패턴', likes: 589 },
    ],
  },
];
